// Generated by SwikiGraphQLOperationGenerator
// DO NOT EDIT - regenerate from GraphQLOperations/*.graphql

import Foundation
import GraphQL

public extension SwikiGraphQLOperations {
    struct DefaultMangasOperation: SwikiGraphQLOperation {
        public static let operationName: String? = "DefaultMangas"
        public static let operationDocument: String = """
        query DefaultMangas(
          $page: PositiveInt = 1
          $limit: PositiveInt = 1
          $search: String
        ) {
          mangas(page: $page, limit: $limit, search: $search) {
            id
            malId
            name
            russian
            licenseNameRu
            english
            japanese
            synonyms
            kind
            score
            status
            volumes
            chapters
            airedOn { year month day date }
            releasedOn { year month day date }
            url
        
            poster { id originalUrl mainUrl }
        
            licensors
            createdAt
            updatedAt
            isCensored
        
            genres { id name russian kind }
            publishers { id name }
        
            externalLinks {
              id
              kind
              url
              createdAt
              updatedAt
            }
        
            personRoles {
              id
              rolesRu
              rolesEn
              person { id name poster { id } }
            }
            characterRoles {
              id
              rolesRu
              rolesEn
              character { id name poster { id } }
            }
        
            related {
              id
              anime {
                id
                name
              }
              manga {
                id
                name
              }
              relationKind
              relationText
            }
        
            scoresStats { score count }
            statusesStats { status count }
        
            description
            descriptionHtml
            descriptionSource
          }
        }
        """

        public struct Variables: Encodable, Sendable {
            public let page: Int?
            public let limit: Int?
            public let search: String?

            public init(page: Int? = nil, limit: Int? = nil, search: String? = nil) {
                self.page = page
                self.limit = limit
                self.search = search
            }
        }

        public let variables: Variables
        public init(variables: Variables) {
            self.variables = variables
        }

        public struct Data: Decodable, Sendable {
            public let mangas: [MangasItem]

            public struct MangasItem: Decodable, Sendable {
                public let id: String
                public let malId: String?
                public let name: String
                public let russian: String?
                public let licenseNameRu: String?
                public let english: String?
                public let japanese: String?
                public let synonyms: [String]
                public let kind: SwikiMangaKind?
                public let score: Double?
                public let status: SwikiMangaStatus?
                public let volumes: Int
                public let chapters: Int
                public let airedOn: SwikiIncompleteDate?
                public let releasedOn: SwikiIncompleteDate?
                public let url: String
                public let poster: Poster?
                public let licensors: [String]?
                public let createdAt: Date
                public let updatedAt: Date
                public let isCensored: Bool?
                public let genres: [GenresItem]?
                public let publishers: [PublishersItem]
                public let externalLinks: [ExternalLinksItem]?
                public let personRoles: [PersonRolesItem]?
                public let characterRoles: [CharacterRolesItem]?
                public let related: [RelatedItem]?
                public let scoresStats: [ScoresStatsItem]?
                public let statusesStats: [StatusesStatsItem]?
                public let description: String?
                public let descriptionHtml: String?
                public let descriptionSource: String?

                public struct Poster: Decodable, Sendable {
                    public let id: String
                    public let originalUrl: String
                    public let mainUrl: String
                }

                public struct GenresItem: Decodable, Sendable {
                    public let id: String
                    public let name: String
                    public let russian: String
                    public let kind: SwikiGenreKind
                }

                public struct PublishersItem: Decodable, Sendable {
                    public let id: String
                    public let name: String
                }

                public struct ExternalLinksItem: Decodable, Sendable {
                    public let id: String?
                    public let kind: SwikiExternalLinkKind
                    public let url: String
                    public let createdAt: Date?
                    public let updatedAt: Date?
                }

                public struct PersonRolesItem: Decodable, Sendable {
                    public let id: String
                    public let rolesRu: [String]
                    public let rolesEn: [String]
                    public let person: Person

                    public struct Person: Decodable, Sendable {
                        public let id: String
                        public let name: String
                        public let poster: Poster?

                        public struct Poster: Decodable, Sendable {
                            public let id: String
                        }
                    }
                }

                public struct CharacterRolesItem: Decodable, Sendable {
                    public let id: String
                    public let rolesRu: [String]
                    public let rolesEn: [String]
                    public let character: Character

                    public struct Character: Decodable, Sendable {
                        public let id: String
                        public let name: String
                        public let poster: Poster?

                        public struct Poster: Decodable, Sendable {
                            public let id: String
                        }
                    }
                }

                public struct RelatedItem: Decodable, Sendable {
                    public let id: String
                    public let anime: Anime?
                    public let manga: Manga?
                    public let relationKind: SwikiRelationKind
                    public let relationText: String

                    public struct Anime: Decodable, Sendable {
                        public let id: String
                        public let name: String
                    }

                    public struct Manga: Decodable, Sendable {
                        public let id: String
                        public let name: String
                    }
                }

                public struct ScoresStatsItem: Decodable, Sendable {
                    public let score: Int
                    public let count: Int
                }

                public struct StatusesStatsItem: Decodable, Sendable {
                    public let status: SwikiUserRateStatus
                    public let count: Int
                }
            }
        }
    }
}
