// Generated by SwikiGraphQLOperationGenerator
// DO NOT EDIT - regenerate from GraphQLOperations/*.graphql

import Foundation
import GraphQL

public extension SwikiGraphQLOperations {
    struct DefaultPeopleOperation: SwikiGraphQLOperation {
        public static let operationName: String? = "DefaultPeople"
        public static let operationDocument: String = """
        query DefaultPeople(
          $page: PositiveInt = 1
          $limit: PositiveInt = 1
          $search: String
          $isSeyu: Boolean
          $isProducer: Boolean
          $isMangaka: Boolean
        ) {
          people(
            page: $page
            limit: $limit
            search: $search
            isSeyu: $isSeyu
            isProducer: $isProducer
            isMangaka: $isMangaka
          ) {
            id
            malId
            name
            russian
            japanese
            synonyms
            url
            isSeyu
            isMangaka
            isProducer
            website
            createdAt
            updatedAt
            birthOn { year month day date }
            deceasedOn { year month day date }
        
            poster { id originalUrl mainUrl }
          }
        }
        """

        public struct Variables: Encodable, Sendable {
            public let page: Int?
            public let limit: Int?
            public let search: String?
            public let isSeyu: Bool?
            public let isProducer: Bool?
            public let isMangaka: Bool?

            public init(page: Int? = nil, limit: Int? = nil, search: String? = nil, isSeyu: Bool? = nil, isProducer: Bool? = nil, isMangaka: Bool? = nil) {
                self.page = page
                self.limit = limit
                self.search = search
                self.isSeyu = isSeyu
                self.isProducer = isProducer
                self.isMangaka = isMangaka
            }
        }

        public let variables: Variables
        public init(variables: Variables) {
            self.variables = variables
        }

        public struct Data: Decodable, Sendable {
            public let people: [PeopleItem]

            public struct PeopleItem: Decodable, Sendable {
                public let id: String
                public let malId: String?
                public let name: String
                public let russian: String?
                public let japanese: String?
                public let synonyms: [String]
                public let url: String
                public let isSeyu: Bool
                public let isMangaka: Bool
                public let isProducer: Bool
                public let website: String?
                public let createdAt: Date
                public let updatedAt: Date
                public let birthOn: SwikiIncompleteDate?
                public let deceasedOn: SwikiIncompleteDate?
                public let poster: Poster?

                public struct Poster: Decodable, Sendable {
                    public let id: String
                    public let originalUrl: String
                    public let mainUrl: String
                }
            }
        }
    }
}
