// Generated by SwikiGraphQLOperationGenerator
// DO NOT EDIT - regenerate from GraphQLOperations/*.graphql

import Foundation
import GraphQL

public extension SwikiGraphQLOperations {
    struct DefaultCharactersOperation: SwikiGraphQLOperation {
        public static let operationName: String? = "DefaultCharacters"
        public static let operationDocument: String = """
        query DefaultCharacters(
          $page: PositiveInt = 1
          $limit: PositiveInt = 1
          $search: String
        ) {
          characters(page: $page, limit: $limit, search: $search) {
            id
            malId
            name
            russian
            japanese
            synonyms
            url
            createdAt
            updatedAt
            isAnime
            isManga
            isRanobe
        
            poster { id originalUrl mainUrl }
        
            description
            descriptionHtml
            descriptionSource
          }
        }
        """

        public struct Variables: Encodable, Sendable {
            public let page: Int?
            public let limit: Int?
            public let search: String?

            public init(page: Int? = nil, limit: Int? = nil, search: String? = nil) {
                self.page = page
                self.limit = limit
                self.search = search
            }
        }

        public let variables: Variables
        public init(variables: Variables) {
            self.variables = variables
        }

        public struct Data: Decodable, Sendable {
            public let characters: [CharactersItem]

            public struct CharactersItem: Decodable, Sendable {
                public let id: String
                public let malId: String?
                public let name: String
                public let russian: String?
                public let japanese: String?
                public let synonyms: [String]
                public let url: String
                public let createdAt: Date
                public let updatedAt: Date
                public let isAnime: Bool
                public let isManga: Bool
                public let isRanobe: Bool
                public let poster: Poster?
                public let description: String?
                public let descriptionHtml: String?
                public let descriptionSource: String?

                public struct Poster: Decodable, Sendable {
                    public let id: String
                    public let originalUrl: String
                    public let mainUrl: String
                }
            }
        }
    }
}
