// Generated by SwikiGraphQLOperationGenerator
// DO NOT EDIT - regenerate from GraphQLOperations/*.graphql

import Foundation
import GraphQL

public extension SwikiGraphQLOperations {
    struct DefaultUserRatesOperation: SwikiGraphQLOperation {
        public static let operationName: String? = "DefaultUserRates"
        public static let operationDocument: String = """
        query DefaultUserRates(
          $page: PositiveInt = 1
          $limit: PositiveInt = 5
          $userId: ID
          $targetType: UserRateTargetTypeEnum = Anime
          $status: UserRateStatusEnum
          $orderField: UserRateOrderFieldEnum = updated_at
          $sortOrder: SortOrderEnum = desc
        ) {
          userRates(
            page: $page
            limit: $limit
            userId: $userId
            targetType: $targetType
            status: $status
            order: { field: $orderField, order: $sortOrder }
          ) {
            id
            anime { id name }
            createdAt
          }
        }
        """

        public struct Variables: Encodable, Sendable {
            public let page: Int?
            public let limit: Int?
            public let userId: String?
            public let targetType: SwikiUserRateTargetType?
            public let status: SwikiUserRateStatus?
            public let orderField: SwikiUserRateOrderField?
            public let sortOrder: SwikiSortOrderType?

            public init(page: Int? = nil, limit: Int? = nil, userId: String? = nil, targetType: SwikiUserRateTargetType? = nil, status: SwikiUserRateStatus? = nil, orderField: SwikiUserRateOrderField? = nil, sortOrder: SwikiSortOrderType? = nil) {
                self.page = page
                self.limit = limit
                self.userId = userId
                self.targetType = targetType
                self.status = status
                self.orderField = orderField
                self.sortOrder = sortOrder
            }
        }

        public let variables: Variables
        public init(variables: Variables) {
            self.variables = variables
        }

        public struct Data: Decodable, Sendable {
            public let userRates: [UserRatesItem]

            public struct UserRatesItem: Decodable, Sendable {
                public let id: String
                public let anime: Anime?
                public let createdAt: Date

                public struct Anime: Decodable, Sendable {
                    public let id: String
                    public let name: String
                }
            }
        }
    }
}
