// Generated by SwikiGraphQLOperationGenerator
// DO NOT EDIT - regenerate from GraphQLOperations/*.graphql

import Foundation
import GraphQL

public extension SwikiGraphQLOperations {
    struct DefaultAnimesOperation: SwikiGraphQLOperation {
        public static let operationName: String? = "DefaultAnimes"
        public static let operationDocument: String = """
        query DefaultAnimes(
          $search: String = "bakemono"
          $limit: PositiveInt = 1
          $kind: AnimeKindString = "!special"
        ) {
          animes(search: $search, limit: $limit, kind: $kind) {
            id
            malId
            name
            russian
            licenseNameRu
            english
            japanese
            synonyms
            kind
            rating
            score
            status
            episodes
            episodesAired
            duration
            airedOn { year month day date }
            releasedOn { year month day date }
            url
            season
        
            poster { id originalUrl mainUrl }
        
            fansubbers
            fandubbers
            licensors
            createdAt
            updatedAt
            nextEpisodeAt
            isCensored
        
            genres { id name russian kind }
            studios { id name imageUrl }
        
            externalLinks {
              id
              kind
              url
              createdAt
              updatedAt
            }
        
            personRoles {
              id
              rolesRu
              rolesEn
              person { id name poster { id } }
            }
            characterRoles {
              id
              rolesRu
              rolesEn
              character { id name poster { id } }
            }
        
            related {
              id
              anime {
                id
                name
              }
              manga {
                id
                name
              }
              relationKind
              relationText
            }
        
            videos { id url name kind playerUrl imageUrl }
            screenshots { id originalUrl x166Url x332Url }
        
            scoresStats { score count }
            statusesStats { status count }
        
            description
            descriptionHtml
            descriptionSource
          }
        }
        """

        public struct Variables: Encodable, Sendable {
            public let search: String?
            public let limit: Int?
            public let kind: String?

            public init(search: String? = nil, limit: Int? = nil, kind: String? = nil) {
                self.search = search
                self.limit = limit
                self.kind = kind
            }
        }

        public let variables: Variables
        public init(variables: Variables) {
            self.variables = variables
        }

        public struct Data: Decodable, Sendable {
            public let animes: [AnimesItem]

            public struct AnimesItem: Decodable, Sendable {
                public let id: String
                public let malId: String?
                public let name: String
                public let russian: String?
                public let licenseNameRu: String?
                public let english: String?
                public let japanese: String?
                public let synonyms: [String]
                public let kind: SwikiAnimeKind?
                public let rating: SwikiAnimeRating?
                public let score: Double?
                public let status: SwikiAnimeStatus?
                public let episodes: Int
                public let episodesAired: Int
                public let duration: Int?
                public let airedOn: SwikiIncompleteDate?
                public let releasedOn: SwikiIncompleteDate?
                public let url: String
                public let season: String?
                public let poster: Poster?
                public let fansubbers: [String]
                public let fandubbers: [String]
                public let licensors: [String]?
                public let createdAt: Date
                public let updatedAt: Date
                public let nextEpisodeAt: Date?
                public let isCensored: Bool?
                public let genres: [GenresItem]?
                public let studios: [StudiosItem]
                public let externalLinks: [ExternalLinksItem]?
                public let personRoles: [PersonRolesItem]?
                public let characterRoles: [CharacterRolesItem]?
                public let related: [RelatedItem]?
                public let videos: [VideosItem]
                public let screenshots: [ScreenshotsItem]
                public let scoresStats: [ScoresStatsItem]?
                public let statusesStats: [StatusesStatsItem]?
                public let description: String?
                public let descriptionHtml: String?
                public let descriptionSource: String?

                public struct Poster: Decodable, Sendable {
                    public let id: String
                    public let originalUrl: String
                    public let mainUrl: String
                }

                public struct GenresItem: Decodable, Sendable {
                    public let id: String
                    public let name: String
                    public let russian: String
                    public let kind: SwikiGenreKind
                }

                public struct StudiosItem: Decodable, Sendable {
                    public let id: String
                    public let name: String
                    public let imageUrl: String?
                }

                public struct ExternalLinksItem: Decodable, Sendable {
                    public let id: String?
                    public let kind: SwikiExternalLinkKind
                    public let url: String
                    public let createdAt: Date?
                    public let updatedAt: Date?
                }

                public struct PersonRolesItem: Decodable, Sendable {
                    public let id: String
                    public let rolesRu: [String]
                    public let rolesEn: [String]
                    public let person: Person

                    public struct Person: Decodable, Sendable {
                        public let id: String
                        public let name: String
                        public let poster: Poster?

                        public struct Poster: Decodable, Sendable {
                            public let id: String
                        }
                    }
                }

                public struct CharacterRolesItem: Decodable, Sendable {
                    public let id: String
                    public let rolesRu: [String]
                    public let rolesEn: [String]
                    public let character: Character

                    public struct Character: Decodable, Sendable {
                        public let id: String
                        public let name: String
                        public let poster: Poster?

                        public struct Poster: Decodable, Sendable {
                            public let id: String
                        }
                    }
                }

                public struct RelatedItem: Decodable, Sendable {
                    public let id: String
                    public let anime: Anime?
                    public let manga: Manga?
                    public let relationKind: SwikiRelationKind
                    public let relationText: String

                    public struct Anime: Decodable, Sendable {
                        public let id: String
                        public let name: String
                    }

                    public struct Manga: Decodable, Sendable {
                        public let id: String
                        public let name: String
                    }
                }

                public struct VideosItem: Decodable, Sendable {
                    public let id: String
                    public let url: String
                    public let name: String?
                    public let kind: SwikiVideoKind
                    public let playerUrl: String
                    public let imageUrl: String
                }

                public struct ScreenshotsItem: Decodable, Sendable {
                    public let id: String
                    public let originalUrl: String
                    public let x166Url: String
                    public let x332Url: String
                }

                public struct ScoresStatsItem: Decodable, Sendable {
                    public let score: Int
                    public let count: Int
                }

                public struct StatusesStatsItem: Decodable, Sendable {
                    public let status: SwikiUserRateStatus
                    public let count: Int
                }
            }
        }
    }
}
